version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: payment-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_reconciliation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api-gateway/migrations:/docker-entrypoint-initdb.d   # автоматически выполнит SQL при первом запуске
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api-gateway
    container_name: payment-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/payment_reconciliation?sslmode=disable
      # REDIS_ADDR: redis:6379   # пока закомментировано, т.к. WebSocket не используется
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data: