FROM golang:1.22-alpine AS builder

# Настройка прокси для быстрой загрузки зависимостей
ENV GOPROXY=https://proxy.golang.org,direct

WORKDIR /app

# Копируем go.mod и go.sum для кэширования зависимостей
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходный код
COPY . .

# Собираем приложение
RUN go build -o emulator-bank .

# Финальный образ
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/emulator-bank .
CMD ["./emulator-bank"]